# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\31136\Desktop\demo\demo1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from utills import *
import json


class Ui_MainWindow(object):
    def __init__(self):
        self.statusbar = None
        self.menu = None
        self.menubar = None
        self.textEdit = None
        self.pushButton = None
        self.gridLayout = None
        self.formLayoutWidget = None
        self.centralwidget = None
        self.audio = None
        self.chatbot = chatbot()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 608)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(198, 198, 198);\n"
                                 "font: 17pt \"隶书\";")
        self.audio = Audio()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 40, 691, 401))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setStyleSheet("border-color: rgb(170, 255, 255);\n"
                                      "background-color: rgb(170, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.pressed.connect(self.record)
        self.pushButton.released.connect(self.play)

        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)

        self.textEdit = ChatBox(self.formLayoutWidget)
        # self.textEdit =  QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit.load()
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "按住录音，松开发送"))
        self.menu.setTitle(_translate("MainWindow", "对话界面"))

    def record(self):
        self.audio.record()

    def play(self):
        text = self.audio.stop()
        self.textEdit.append('user: ' + text)
        answer = self.answer(text)
        self.textEdit.append('chatbot: ' + answer)
        self.audio.play(answer)
        # self.textEdit.save()
        print('finished')

    def answer(self, text):
        answer = self.chatbot.get_completion(prompt=text)
        return answer


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
